name: Mirror WGCF (Fixed Tag)

on:
  schedule:
    - cron: '0 2 * * 1'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  mirror_wgcf:
    name: Sync WGCF
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Version
        run: |
          TAG=$(curl -sL https://api.github.com/repos/ViRb3/wgcf/releases/latest | jq -r ".tag_name")
          VERSION="${TAG#v}"
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Download
        run: |
          mkdir -p dist
          wget -O dist/wgcf_linux_amd64 "https://github.com/ViRb3/wgcf/releases/download/${TAG}/wgcf_${VERSION}_linux_amd64"
          wget -O dist/wgcf_linux_arm64 "https://github.com/ViRb3/wgcf/releases/download/${TAG}/wgcf_${VERSION}_linux_arm64"
          chmod +x dist/*

      - name: Generate Individual Checksums
        run: |
          cd dist
          sha256sum wgcf_linux_amd64 > wgcf_linux_amd64.sha256
          sha256sum wgcf_linux_arm64 > wgcf_linux_arm64.sha256

      - name: Publish to 'wgcf-latest'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "wgcf-latest"
          name: "WGCF (Auto-Updated)"
          body: "Synced from ${TAG} on $(date)"
          make_latest: false
          files: dist/*
